### ISSUE TITLE
Fix failing import for scorer worker celery task

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/osome-csdl-ranking-challenge#9]
Per title. This should require just 
- [X] Specify the qualified name of the scorer worker's subpackage when computing score batches.
- [X] Make sure embedded URLs in user posts are serialized to JSON before adding them to the task queue
- [X] Load the models on scorer worker startup
- [x] Fix batch scoring, use ThreadPoolExecutor

**Comment by glciampaglia** [comment]
Fixed most obvious errors, now getting this:
```python
ranker_1                 | 2024-07-06 04:12:17,750 - INFO - dante.app.ranking_server.ranking_server - Received ranking request
ranker_1                 | 2024-07-06 04:12:17,753 - INFO - dante.app.scorer_worker.scorer_basic - Sending the task group
ranker_1                 | INFO:     172.21.0.1:54382 - "POST /rank HTTP/1.1" 500 Internal Server Error
ranker_1                 | ERROR:    Exception in ASGI application
ranker_1                 | Traceback (most recent call last):
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/kombu/serialization.py", line 41, in _reraise_errors
ranker_1                 |     yield
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/kombu/serialization.py", line 220, in dumps
ranker_1                 |     payload = encoder(data)
ranker_1                 |               ^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/kombu/utils/json.py", line 63, in dumps
ranker_1                 |     return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))
ranker_1                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
ranker_1                 |     **kw).encode(obj)
ranker_1                 |           ^^^^^^^^^^^
ranker_1                 |   File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
ranker_1                 |     chunks = self.iterencode(o, _one_shot=True)
ranker_1                 |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
ranker_1                 |     return _iterencode(o, 0)
ranker_1                 |            ^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/kombu/utils/json.py", line 47, in default
ranker_1                 |     return super().default(o)
ranker_1                 |            ^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
ranker_1                 |     raise TypeError(f'Object of type {o.__class__.__name__} '
ranker_1                 | TypeError: Object of type Url is not JSON serializable
ranker_1                 |
ranker_1                 | During handling of the above exception, another exception occurred:
ranker_1                 |
ranker_1                 | Traceback (most recent call last):
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
ranker_1                 |     result = await app(  # type: ignore[func-returns-value]
ranker_1                 |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
ranker_1                 |     return await self.app(scope, receive, send)
ranker_1                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
ranker_1                 |     await super().__call__(scope, receive, send)
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
ranker_1                 |     await self.middleware_stack(scope, receive, send)
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
ranker_1                 |     raise exc
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
ranker_1                 |     await self.app(scope, receive, _send)
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
ranker_1                 |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
ranker_1                 |     raise exc
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
ranker_1                 |     await app(scope, receive, sender)
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
ranker_1                 |     await self.middleware_stack(scope, receive, send)
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
ranker_1                 |     await route.handle(scope, receive, send)
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
ranker_1                 |     await self.app(scope, receive, send)
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
ranker_1                 |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
ranker_1                 |     raise exc
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
ranker_1                 |     await app(scope, receive, sender)
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
ranker_1                 |     response = await func(request)
ranker_1                 |                ^^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
ranker_1                 |     raw_response = await run_endpoint_function(
ranker_1                 |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
ranker_1                 |     return await run_in_threadpool(dependant.call, **values)
ranker_1                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
ranker_1                 |     return await anyio.to_thread.run_sync(func, *args)
ranker_1                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
ranker_1                 |     return await get_async_backend().run_sync_in_worker_thread(
ranker_1                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
ranker_1                 |     return await future
ranker_1                 |            ^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 859, in run
ranker_1                 |     result = context.run(func, *args)
ranker_1                 |              ^^^^^^^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/dante/app/ranking_server/ranking_server.py", line 150, in rank
ranker_1                 |     har_scores = compute_batch_scores(
ranker_1                 |                  ^^^^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/dante/app/scorer_worker/scorer_basic.py", line 111, in compute_batch_scores
ranker_1                 |     async_result = group(tasks).apply_async()
ranker_1                 |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/celery/canvas.py", line 1614, in apply_async
ranker_1                 |     results = list(self._apply_tasks(tasks, producer, app, p,
ranker_1                 |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/celery/canvas.py", line 1793, in _apply_tasks
ranker_1                 |     sig.apply_async(producer=producer, add_to_parent=False,
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/celery/canvas.py", line 400, in apply_async
ranker_1                 |     return _apply(args, kwargs, **options)
ranker_1                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/celery/app/task.py", line 594, in apply_async
ranker_1                 |     return app.send_task(
ranker_1                 |            ^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/celery/app/base.py", line 801, in send_task
ranker_1                 |     amqp.send_task_message(P, name, message, **options)
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/celery/app/amqp.py", line 518, in send_task_message
ranker_1                 |     ret = producer.publish(
ranker_1                 |           ^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/kombu/messaging.py", line 175, in publish
ranker_1                 |     body, content_type, content_encoding = self._prepare(
ranker_1                 |                                            ^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/kombu/messaging.py", line 268, in _prepare
ranker_1                 |     body) = dumps(body, serializer=serializer)
ranker_1                 |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/kombu/serialization.py", line 219, in dumps
ranker_1                 |     with _reraise_errors(EncodeError):
ranker_1                 |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
ranker_1                 |     self.gen.throw(value)
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/kombu/serialization.py", line 45, in _reraise_errors
ranker_1                 |     reraise(wrapper, wrapper(exc), sys.exc_info()[2])
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/kombu/exceptions.py", line 34, in reraise
ranker_1                 |     raise value.with_traceback(tb)
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/kombu/serialization.py", line 41, in _reraise_errors
ranker_1                 |     yield
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/kombu/serialization.py", line 220, in dumps
ranker_1                 |     payload = encoder(data)
ranker_1                 |               ^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/kombu/utils/json.py", line 63, in dumps
ranker_1                 |     return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))
ranker_1                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
ranker_1                 |     **kw).encode(obj)
ranker_1                 |           ^^^^^^^^^^^
ranker_1                 |   File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
ranker_1                 |     chunks = self.iterencode(o, _one_shot=True)
ranker_1                 |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
ranker_1                 |     return _iterencode(o, 0)
ranker_1                 |            ^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/app/.venv/lib/python3.12/site-packages/kombu/utils/json.py", line 47, in default
ranker_1                 |     return super().default(o)
ranker_1                 |            ^^^^^^^^^^^^^^^^^^
ranker_1                 |   File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
ranker_1                 |     raise TypeError(f'Object of type {o.__class__.__name__} '
ranker_1                 | kombu.exceptions.EncodeError: Object of type Url is not JSON serializable
```

**Comment by glciampaglia** [comment]
The issue was due to [adding embedded URLs from the POST data](https://github.com/glciampaglia/osome-csdl-ranking-challenge/blob/f8ae956fdb9f37fa4a331e7a79b52e92bee90dbf/dante/app/ranking_server/ranking_server.py#L144) among the task inputs the scorer worker. Anything that goes into Celery needs to be serialized (I believe to JSON). Celery uses a library called [kombu](https://docs.celeryq.dev/projects/kombu/en/stable/) and it seems this library is not able to serialize that particular type (`pydantic.networks.Url`) by default. 

Since URLs need to be sent to the scraper worker for unshortening we may skip this step anyway, as long as the scorer has a way to know *which* URLs were present in the POST data. That said the scraper worker too uses Celery to communicate so we probably need to figure out how to solve this serialization issue. Possible solutions could be to switch to pickle from JSON as a serialization backend, or to [register a custom serialization function](https://docs.celeryq.dev/projects/kombu/en/stable/) for Pydantic URLS.

**Comment by glciampaglia** [comment]
This was solved by using a [utility function](https://fastapi.tiangolo.com/tutorial/encoder/) from FastAPI.
